version: "3.4"
services:
  rethinkdbYN:
    container_name: RethinkDBYN
    build: ./rethinkdb/
    ports:
      - 7374:8080
    restart: always
    volumes:
      - ./rethinkdb/rethinkdb_data:/data/rethinkdb_data
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://localhost:8080"]
      interval: 300s
      timeout: 400s
      retries: 10
  backup:
    container_name: Backup
    build: ./backup/
    restart: always
    volumes:
      - ./backup/backups:/backups
    depends_on:
      - rethinkdbYN
  yardimNerede:
    container_name: YardimNerede
    build:
      context: ./app
      target: production
      dockerfile: Dockerfile
    command: yarn start
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=7376
      - SERVER_ADDRESS=https://yardimnerede.com.tr
      - DOMAIN=yardimnerede.com.tr
    ports:
      - 7376:7376
    depends_on:
      - rethinkdbYN
