version: "3.4"
services:
  rethinkdbYN:
    container_name: RethinkDBYN
    build: ./rethinkdb/
    ports:
      - 7373:8080
    restart: always
    volumes:
      - ./rethinkdb/rethinkdb_data:/data/rethinkdb_data
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://localhost:8080"]
      interval: 300s
      timeout: 400s
      retries: 10
  yardimNerede:
    container_name: yardimNerede
    build:
      context: ./app
      target: development
      dockerfile: Dockerfile
    command: yarn dev
    restart: always
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=7375
      - SERVER_ADDRESS=http://localhost
    ports:
      - 7375:7375
    depends_on:
      - rethinkdbYN
