version: "3.4"
services:
  rethinkdb:
    container_name: RethinkDB
    build: ./rethinkdb/
    ports:
      - YOUR_RETHINKDB_PORT:8080
    restart: always
    volumes:
      - ./rethinkdb/rethinkdb_data:/data/rethinkdb_data
    healthcheck:
      test: ["CMD", "curl", "-fk", "http://localhost:8080"]
      interval: 300s
      timeout: 400s
      retries: 10
  YOUR_APP_NAME:
    container_name: YOUR_APP_NAME
    build:
      context: ./app
      target: development
      dockerfile: Dockerfile
    command: yarn dev
    restart: always
    volumes:
      - ./app:/usr/app
      - /usr/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=YOUR_APP_DEVELOPMENT_PORT
      - SERVER_ADDRESS=http://localhost
    ports:
      - YOUR_APP_DEVELOPMENT_PORT:YOUR_APP_DEVELOPMENT_PORT
    depends_on:
      - rethinkdb
